a=int(input("Base of input"))
b=int(input())
s=input()
if '.' in s:
    i,f=s.split('.')
else:
    i=s
    f=""
if(a==10 and b==2):
    n=int(i)
    b=""
    while(n!=0):
        b=str(n%2)+b
        n=n//2
    fr=0
    if(f==""):
        print(b)
    else:
        l=len(f)
        fr=int(f)/10**l
        i=0
        b=b+"."
        while(fr!=0 and i<10):
            fr=fr*2
            b=b+str(int(fr))
            fr=fr-int(fr)
            i=i+1
        print(b)
elif(a==16 and b==2):
    b=""
    c=s[0]
    if(c=='1'):
        b=b+"1"
    elif(c=='2'):
        b=b+"10"
    elif(c=='3'):
        b=b+"11"
    elif(c=='4'):
        b=b+"100"
    elif(c=='5'):
        b=b+"101"
    elif(c=='6'):
        b=b+"110"
    elif(c=='7'):
        b=b+"111"
    elif(c=='8'):
        b=b+"1000"
    elif(c=='9'):
        b=b+"1001"
    elif(c=='A'):
        b=b+"1010"
    elif(c=='B'):
        b=b+"1011"
    elif(c=='C'):
        b=b+"1100"
    elif(c=='D'):
        b=b+"1101"
    elif(c=='E'):
        b=b+"1110"
    elif(c=='F'):
        b=b+"1111"
    elif(c=='0'):
        b=b+"0000"
    s=s[1:]
    for c in s:
        if(c=='1'):
            b=b+"0001"
        elif(c=='2'):
            b=b+"0010"
        elif(c=='3'):
            b=b+"0011"
        elif(c=='4'):
            b=b+"0100"
        elif(c=='5'):
            b=b+"0101"
        elif(c=='6'):
            b=b+"0110"
        elif(c=='7'):
            b=b+"0111"
        elif(c=='8'):
            b=b+"1000"
        elif(c=='9'):
            b=b+"1001"
        elif(c=='A'):
            b=b+"1010"
        elif(c=='B'):
            b=b+"1011"
        elif(c=='C'):
            b=b+"1100"
        elif(c=='D'):
            b=b+"1101"
        elif(c=='E'):
            b=b+"1110"
        elif(c=='F'):
            b=b+"1111"
        elif(c=='.'):
            b=b+"."
        elif(c=='0'):
            b=b+"0000"
    print(b)
elif(a==8 and b==16):
    b=""
    c=s[0]
    if(c=='1'):
        b=b+"1"
    elif(c=='2'):
        b=b+"10"
    elif(c=='3'):
        b=b+"11"
    elif(c=='4'):
        b=b+"100"
    elif(c=='5'):
        b=b+"101"
    elif(c=='6'):
        b=b+"110"
    elif(c=='7'):
        b=b+"111"
    elif(c=='0'):
        b=b+"000"
    s=s[1:]
    for c in s:
        if(c=='1'):
            b=b+"001"
        elif(c=='2'):
            b=b+"010"
        elif(c=='3'):
            b=b+"011"
        elif(c=='4'):
            b=b+"100"
        elif(c=='5'):
            b=b+"101"
        elif(c=='6'):
            b=b+"110"
        elif(c=='7'):
            b=b+"111"
        elif(c=='.'):
            b=b+"."
        elif(c=='0'):
            b=b+"000"
    if '.' in b:
        i,f=b.split('.')
    else:
        i=b
        f=""
    li=len(i)
    j=0
    while(li%4!=0 and j<4-li%4):
        i="0"+i
        j=j+1
    lf=len(f)
    j=0
    while(lf%4!=0 and j<4-lf%4):
        f=f+"0"
        j=j+1
    j=0
    o=""
    #print(i)
    while(j<len(i)):
        ss=i[j:j+4]
        if(ss=="0001"):
            o=o+"1"
        elif(ss=="0010"):
            o=o+"2"  
        elif(ss=="0011"):
            o=o+"3" 
        elif(ss=="0100"):
            o=o+"4"
        elif(ss=="0101"):
            o=o+"5"
        elif(ss=="0110"):
            o=o+"6"
        elif(ss=="0111"):
            o=o+"7" 
        elif(ss=="1000"):
            o=o+"8" 
        elif(ss=="1001"):
            o=o+"9"
        elif(ss=="1010"):
            o=o+"A"
        elif(ss=="1011"):
            o=o+"B"
        elif(ss=="1100"):
            o=o+"C"
        elif(ss=="1101"):
            o=o+"D"
        elif(ss=="1110"):
            o=o+"E"
        elif(ss=="1111"):
            o=o+"F"
        elif(ss=="0000"):
            o=o+"0"
        j=j+4
        #print(ss)
    if(f==""):
        print(o)
    else:
        j=0
        o=o+"."
        while(j<len(f)):
            ss=f[j:j+4]
            if(ss=="0001"):
                o=o+"1"
            elif(ss=="0010"):
                o=o+"2"  
            elif(ss=="0011"):
                o=o+"3" 
            elif(ss=="0100"):
                o=o+"4"
            elif(ss=="0101"):
                o=o+"5"
            elif(ss=="0110"):
                o=o+"6"
            elif(ss=="0111"):
                o=o+"7" 
            elif(ss=="1000"):
                o=o+"8" 
            elif(ss=="1001"):
                o=o+"9"
            elif(ss=="1010"):
                o=o+"A"
            elif(ss=="1011"):
                o=o+"B"
            elif(ss=="1100"):
                o=o+"C"
            elif(ss=="1101"):
                o=o+"D"
            elif(ss=="1110"):
                o=o+"E"
            elif(ss=="1111"):
                o=o+"F"
            elif(ss=="0000"):
                o=o+"0"
            j=j+4
        print(o)
elif(a==16 and b==8):
    b=""
    c=s[0]
    if(c=='1'):
        b=b+"1"
    elif(c=='2'):
        b=b+"10"
    elif(c=='3'):
        b=b+"11"
    elif(c=='4'):
        b=b+"100"
    elif(c=='5'):
        b=b+"101"
    elif(c=='6'):
        b=b+"110"
    elif(c=='7'):
        b=b+"111"
    elif(c=='8'):
        b=b+"1000"
    elif(c=='9'):
        b=b+"1001"
    elif(c=='A'):
        b=b+"1010"
    elif(c=='B'):
        b=b+"1011"
    elif(c=='C'):
        b=b+"1100"
    elif(c=='D'):
        b=b+"1101"
    elif(c=='E'):
        b=b+"1110"
    elif(c=='F'):
        b=b+"1111"
    elif(c=='0'):
        b=b+"0000"
    s=s[1:]
    for c in s:
        if(c=='1'):
            b=b+"1"
        elif(c=='2'):
            b=b+"10"
        elif(c=='3'):
            b=b+"11"
        elif(c=='4'):
            b=b+"100"
        elif(c=='5'):
            b=b+"101"
        elif(c=='6'):
            b=b+"110"
        elif(c=='7'):
            b=b+"111"
        elif(c=='8'):
            b=b+"1000"
        elif(c=='9'):
            b=b+"1001"
        elif(c=='A'):
            b=b+"1010"
        elif(c=='B'):
            b=b+"1011"
        elif(c=='C'):
            b=b+"1100"
        elif(c=='D'):
            b=b+"1101"
        elif(c=='E'):
            b=b+"1110"
        elif(c=='F'):
            b=b+"1111"
        elif(c=='.'):
            b=b+"."
        elif(c=='0'):
            b=b+"0000"
    if '.' in b:
        i,f=b.split('.')
    else:
        i=b
        f=""
    li=len(i)
    j=0
    while(li%3!=0 and j<3-li%3):
        i="0"+i
        j=j+1
    lf=len(f)
    j=0
    while(lf%3!=0 and j<3-lf%3):
        f=f+"0"
        j=j+1
    j=0
    o=""
    #print(f)
    while(j<len(i)):
        ss=i[j:j+3]
        if(ss=="001"):
            o=o+"1"
        elif(ss=="010"):
            o=o+"2"  
        elif(ss=="011"):
            o=o+"3" 
        elif(ss=="100"):
            o=o+"4"
        elif(ss=="101"):
            o=o+"5"
        elif(ss=="110"):
            o=o+"6"
        elif(ss=="111"):
            o=o+"7" 
        elif(ss=="000"):
            o=o+"0"
        j=j+3
        #print(ss)
    if(f==""):
        print(o)
    else:
        j=0
        o=o+"."
        while(j<len(f)):
            ss=f[j:j+3]
            if(ss=="001"):
                o=o+"1"
            elif(ss=="010"):
                o=o+"2"  
            elif(ss=="011"):
                o=o+"3" 
            elif(ss=="100"):
                o=o+"4"
            elif(ss=="101"):
                o=o+"5"
            elif(ss=="110"):
                o=o+"6"
            elif(ss=="111"):
                o=o+"7" 
            j=j+3
        print(o)